import { DanceMove, Difficulty } from "./types";

export const SINGLE_MOVES: DanceMove[] = [
  {
    name: "Básico",
    mode: "single",
    audioFile: "single-basico.mp3",
    nextMoves: [
      "Básico",
      "Mambo",
      "Lateral",
      "Cruzado por atrás",
      "Circula",
      "Vuelta izquierda",
      "Vuelta derecha",
      "Un fly",
    ],
  },
  {
    name: "Mambo",
    mode: "single",
    audioFile: "single-mambo.mp3",
    nextMoves: [
      "Básico",
      "Mambo",
      "Lateral",
      "Cruzado por atrás",
      "Circula",
      "Vuelta izquierda",
      "Vuelta derecha",
      "Un fly",
    ],
  },
  {
    name: "Lateral",
    mode: "single",
    audioFile: "single-lateral.mp3",
    nextMoves: [
      "Básico",
      "Mambo",
      "Lateral",
      "Cruzado por atrás",
      "Circula",
      "Vuelta izquierda",
      "Vuelta derecha",
      "Un fly",
    ],
  },
  {
    name: "Cruzado por atrás",
    mode: "single",
    audioFile: "single-cruzado.mp3",
    nextMoves: [
      "Básico",
      "Mambo",
      "Lateral",
      "Cruzado por atrás",
      "Caminamos",
      "Circula",
      "Vuelta izquierda",
      "Vuelta derecha",
      "Un fly",
    ],
  },
  {
    name: "Caminamos",
    mode: "single",
    audioFile: "single-caminamos.mp3",
    nextMoves: [
      "Básico",
      "Mambo",
      "Lateral",
      "Cruzado por atrás",
      "Circula",
      "Vuelta izquierda",
      "Vuelta derecha",
      "Un fly",
    ],
  },
  {
    name: "Circula",
    mode: "single",
    audioFile: "single-circula.mp3",
    nextMoves: [
      "Básico",
      "Mambo",
      "Lateral",
      "Cruzado por atrás",
      "Circula",
      "Vuelta izquierda",
      "Vuelta derecha",
      "Un fly",
    ],
  },
  {
    name: "Vuelta izquierda",
    mode: "single",
    audioFile: "single-vuelta-izq.mp3",
    nextMoves: [
      "Básico",
      "Mambo",
      "Lateral",
      "Cruzado por atrás",
      "Circula",
      "Vuelta izquierda",
      "Vuelta derecha",
      "Un fly",
    ],
  },
  {
    name: "Vuelta derecha",
    mode: "single",
    audioFile: "single-vuelta-der.mp3",
    nextMoves: [
      "Básico",
      "Mambo",
      "Lateral",
      "Cruzado por atrás",
      "Circula",
      "Vuelta izquierda",
      "Vuelta derecha",
      "Un fly",
    ],
  },
  {
    name: "Un fly",
    mode: "single",
    audioFile: "single-un-fly.mp3",
    nextMoves: [
      "Básico",
      "Mambo",
      "Lateral",
      "Cruzado por atrás",
      "Circula",
      "Vuelta izquierda",
      "Vuelta derecha",
      "Un fly",
    ],
  },
];

export const COUPLE_MOVES: DanceMove[] = [
  {
    name: "Básico",
    mode: "couple",
    audioFile: "couple-basico.mp3",
    nextMoves: [
      "Básico",
      "Caminando",
      "Caminamos hacia adelante y cambio de pareja",
      "Es broma",
      "Abajo con salsa",
      "Aspirina",
      "Dile que no",
      "Base cubana",
      "Un fly",
      "Enxufla",
      "Cero",
    ],
  },
  {
    name: "Caminando",
    mode: "couple",
    audioFile: "couple-caminando.mp3",
    nextMoves: [
      "Básico",
      "Caminando",
      "Caminamos hacia adelante y cambio de pareja",
      "Es broma",
      "Abajo con salsa",
      "Aspirina",
      "Dile que no",
      "Base cubana",
      "Un fly",
      "Enxufla",
      "Cero",
    ],
  },
  {
    name: "Caminamos hacia adelante y cambio de pareja",
    mode: "couple",
    audioFile: "couple-caminamos-cambio.mp3",
    nextMoves: [
      "Básico",
      "Caminando",
      "Caminamos hacia adelante y cambio de pareja",
      "Es broma",
      "Abajo con salsa",
      "Aspirina",
      "Dile que no",
      "Base cubana",
      "Un fly",
      "Enxufla",
      "Cero",
    ],
  },
  {
    name: "Es broma",
    mode: "couple",
    audioFile: "couple-es-broma.mp3",
    nextMoves: [
      "Básico",
      "Caminando",
      "Caminamos hacia adelante y cambio de pareja",
      "Es broma",
      "Abajo con salsa",
      "Aspirina",
      "Dile que no",
      "Base cubana",
      "Un fly",
      "Enxufla",
      "Cero",
    ],
  },
  {
    name: "Abajo con salsa",
    mode: "couple",
    audioFile: "couple-abajo.mp3",
    nextMoves: [
      "Básico",
      "Caminando",
      "Caminamos hacia adelante y cambio de pareja",
      "Es broma",
      "Abajo con salsa",
      "Aspirina",
      "Dile que no",
      "Base cubana",
      "Un fly",
      "Enxufla",
      "Cero",
    ],
  },
  {
    name: "Aspirina",
    mode: "couple",
    audioFile: "couple-aspirina.mp3",
    nextMoves: [
      "Básico",
      "Caminando",
      "Caminamos hacia adelante y cambio de pareja",
      "Es broma",
      "Abajo con salsa",
      "Aspirina",
      "Dile que no",
      "Base cubana",
      "Un fly",
      "Enxufla",
      "Cero",
    ],
  },
  {
    name: "Dile que no",
    mode: "couple",
    audioFile: "couple-dile-que-no.mp3",
    nextMoves: [
      "Básico",
      "Caminando",
      "Caminamos hacia adelante y cambio de pareja",
      "Es broma",
      "Abajo con salsa",
      "Aspirina",
      "Dile que no",
      "Base cubana",
      "Un fly",
      "Enxufla",
      "Cero",
    ],
  },
  {
    name: "Base cubana",
    mode: "couple",
    audioFile: "couple-base-cubana.mp3",
    nextMoves: [
      "Básico",
      "Caminando",
      "Caminamos hacia adelante y cambio de pareja",
      "Es broma",
      "Abajo con salsa",
      "Aspirina",
      "Dile que no",
      "Base cubana",
      "Un fly",
      "Enxufla",
      "Cero",
    ],
  },
  {
    name: "Un fly",
    mode: "couple",
    audioFile: "couple-un-fly.mp3",
    nextMoves: [
      "Básico",
      "Caminando",
      "Caminamos hacia adelante y cambio de pareja",
      "Es broma",
      "Abajo con salsa",
      "Aspirina",
      "Dile que no",
      "Base cubana",
      "Un fly",
      "Enxufla",
      "Cero",
    ],
  },
  {
    name: "Enxufla",
    mode: "couple",
    audioFile: "couple-enxufla.mp3",
    nextMoves: [
      "Básico",
      "Caminando",
      "Caminamos hacia adelante y cambio de pareja",
      "Es broma",
      "Abajo con salsa",
      "Aspirina",
      "Dile que no",
      "Base cubana",
      "Un fly",
      "Enxufla",
      "Cero",
    ],
  },
  {
    name: "Cero",
    mode: "couple",
    audioFile: "couple-cero.mp3",
    nextMoves: [
      "Básico",
      "Caminando",
      "Caminamos hacia adelante y cambio de pareja",
      "Es broma",
      "Abajo con salsa",
      "Aspirina",
      "Dile que no",
      "Base cubana",
      "Un fly",
      "Enxufla",
      "Cero",
    ],
  },
];

export const DIFFICULTY_BEATS: Record<
  Difficulty,
  { min: number; max: number }
> = {
  easy: { min: 6, max: 12 },
  medium: { min: 4, max: 10 },
  hard: { min: 2, max: 8 },
};

export const EXAMPLE_PLAYLISTS = {
  youtube: "https://youtu.be/0Xg7jYzQd7g",
  spotify: "https://open.spotify.com/playlist/56KDNXPtjVNWRE86BnXJAQ",
};
